
input_streams:
  # Possible values 'stream', 'file'
  mode: 'file'
  queue_size: 150
  # not effective for mode=file
  retry_limit: 30
  frame_size: [1280, 720, 3]
  # Possible values: either a txt file path or dict
  sources:
    - camera_id: 13
      source: 'Videos/13.mp4'
